### ISSUE TITLE
main loop & threading

### ISSUE THREAD

**Issue by andy128k** [dmitryvk/cl-gtk2#2]
gtk-main should be wrapped by gdk-threads-enter/leave when threading is enabled.

**Comment by dmitryvk** [comment]
Fixed
http://github.com/dmitryvk/cl-gtk2/commit/d6fdd6fff8a86a4f8e106188478e72c451e6363f

**Comment by andy128k** [comment]
I run sbcl on windows (32-bit). cl-gtk2 calls gdk_threads_init, but doesn't wrap gtk-main.

Add same check to invoke of gdk_threads_init or wrap always gtk-main.
